<section id="about">
    <div class="si">
        <div class="eye"><span class="ari">التخصصات</span><span class="eni">Specialties</span></div>
        <h2 class="sh"><span class="ar">خبير في كل جوانب تحسين محركات البحث</span><span class="en">Expert Across All Dimensions of Search Optimization</span></h2>
        <p class="ssub"><span class="ari">خبرة شاملة تغطي SEO التقليدي والذكاء الاصطناعي والمتاجر الإلكترونية — نتائج مثبتة بأرقام حقيقية.</span><span class="eni">Comprehensive expertise covering traditional SEO, AI search, and e-commerce — proven with real numbers.</span></p>
        <div class="spec-grid">
            <div class="spc" data-spc="aisearch" title="اضغط للمزيد"><div class="spc-ico"><i data-lucide="bot"></i></div><div class="spc-name ar">AI Search Optimization</div><div class="spc-name en">AI Search Optimization</div><p class="spc-desc ar">تحسين ظهورك داخل Google AI Overviews وChatGPT وGemini وPerplexity وBing AI.</p><p class="spc-desc en">Optimize visibility inside Google AI Overviews, ChatGPT, Gemini, Perplexity, and Bing AI.</p><span class="ntag">🔥 New</span></div>
            <div class="spc" data-spc="aisearch" title="اضغط للمزيد"><div class="spc-ico"><i data-lucide="zap"></i></div><div class="spc-name ar">AEO — تحسين محركات الإجابات</div><div class="spc-name en">AEO — Answer Engine Optimization</div><p class="spc-desc ar">تحسين المحتوى للظهور في Featured Snippets ومحركات الإجابات والذكاء الاصطناعي.</p><p class="spc-desc en">Optimize content for Featured Snippets, answer engines, and generative AI responses.</p><span class="ntag">🔥 AI</span></div>
            <div class="spc" data-spc="aisearch" title="اضغط للمزيد"><div class="spc-ico"><i data-lucide="globe"></i></div><div class="spc-name ar">GEO — تحسين المحركات التوليدية</div><div class="spc-name en">GEO — Generative Engine Optimization</div><p class="spc-desc ar">تحسين ظهور البراند داخل المحركات التوليدية وبناء هوية رقمية قوية.</p><p class="spc-desc en">Optimize brand visibility inside generative engines and build a strong digital identity.</p><span class="ntag">🔥 AI</span></div>
            <div class="spc" data-spc="cwv" title="اضغط للمزيد"><div class="spc-ico"><i data-lucide="code-2"></i></div><div class="spc-name ar">السيو التقني</div><div class="spc-name en">Technical SEO</div><p class="spc-desc ar">Schema Markup، Crawl Budget، Core Web Vitals، Canonical، وحل مشاكل الأرشفة.</p><p class="spc-desc en">Schema Markup, Crawl Budget, Core Web Vitals, Canonical, and solving all indexation issues.</p></div>
            <div class="spc" data-spc="salla" title="اضغط للمزيد"><div class="spc-ico"><i data-lucide="shopping-bag"></i></div><div class="spc-name ar">سيو المتاجر الإلكترونية</div><div class="spc-name en">Ecommerce SEO</div><p class="spc-desc ar">متخصص في سلة وزد وShopify وWordPress. تحسين المنتجات والفئات لرفع المبيعات.</p><p class="spc-desc en">Specialist in Salla, Zid, Shopify & WordPress. Optimizing products and categories to boost sales.</p></div>
            <div class="spc" data-spc="keyword" title="اضغط للمزيد"><div class="spc-ico"><i data-lucide="cpu"></i></div><div class="spc-name ar">أتمتة SEO بالذكاء الاصطناعي</div><div class="spc-name en">SEO Automation & AI Workflow</div><p class="spc-desc ar">بناء أنظمة ذكية لتسريع تحليل الكلمات المفتاحية وإنشاء المحتوى وتحسين الأرشفة.</p><p class="spc-desc en">Building intelligent systems to accelerate keyword analysis, content creation, and indexation.</p><span class="ntag">🤖 AI</span></div>
        </div>
    </div>
</section>
